//! Comment threads, stored in the open folder so they travel with it (in git,
//! for instance): `.mido/comments/<document path>/<thread id>/<file id>.json`.
//!
//! Files are never changed once written. Each holds a batch of events; the
//! app merges every file of a thread and drops duplicate events. Adding a
//! comment adds a file, and resolving a thread writes one file with all its
//! events and removes the files it replaces. So two people commenting on
//! different branches only ever add or remove different files, and merging
//! them never conflicts.

use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Serialize;

/// Where comments live, relative to the open folder.
pub const COMMENTS_DIR: &str = ".mido/comments";
/// Bigger files are skipped when reading: no comment thread gets that large.
const MAX_FILE_SIZE: u64 = 4 * 1024 * 1024;

#[derive(Serialize, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CommentFile {
    pub thread: String,
    pub name: String,
    pub content: String,
}

/// The comments folder of `document` (inside `root`).
pub fn dir_for(root: &Path, document: &Path) -> Option<PathBuf> {
    let rel = document.strip_prefix(root).ok()?;
    if rel.as_os_str().is_empty() {
        return None;
    }
    Some(root.join(COMMENTS_DIR).join(rel))
}

/// Ids are generated by the app (ULIDs): letters and digits only, which keeps
/// them from naming anything outside their folder.
pub fn valid_id(id: &str) -> bool {
    !id.is_empty() && id.len() <= 64 && id.chars().all(|c| c.is_ascii_alphanumeric())
}

fn check_id(id: &str) -> io::Result<()> {
    if valid_id(id) {
        Ok(())
    } else {
        Err(io::Error::new(io::ErrorKind::InvalidInput, format!("Invalid comment id: {id}")))
    }
}

/// Every comment file of a document, by thread. A document without comments
/// has none.
pub fn read(dir: &Path) -> io::Result<Vec<CommentFile>> {
    let mut out = Vec::new();
    let threads = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(out),
        Err(e) => return Err(e),
    };
    for thread in threads.flatten() {
        let thread_name = thread.file_name().to_string_lossy().into_owned();
        if !valid_id(&thread_name) || !thread.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let Ok(files) = fs::read_dir(thread.path()) else {
            continue;
        };
        for file in files.flatten() {
            let name = file.file_name().to_string_lossy().into_owned();
            let Some(id) = name.strip_suffix(".json") else {
                continue;
            };
            if !valid_id(id) || file.metadata().map(|m| m.len() > MAX_FILE_SIZE).unwrap_or(true) {
                continue;
            }
            if let Ok(content) = fs::read_to_string(file.path()) {
                out.push(CommentFile { thread: thread_name.clone(), name: id.to_string(), content });
            }
        }
    }
    out.sort_by(|a, b| (&a.thread, &a.name).cmp(&(&b.thread, &b.name)));
    Ok(out)
}

/// Writes a new file to a thread. Never replaces an existing file: files are
/// immutable once written.
pub fn add(dir: &Path, thread: &str, name: &str, content: &str) -> io::Result<()> {
    check_id(thread)?;
    check_id(name)?;
    let thread_dir = dir.join(thread);
    fs::create_dir_all(&thread_dir)?;
    // The leading dot keeps the temporary file out of the app's reads.
    let mut tmp = tempfile::Builder::new().prefix(".mido-").suffix(".tmp").tempfile_in(&thread_dir)?;
    tmp.write_all(content.as_bytes())?;
    tmp.as_file().sync_all()?;
    tmp.persist_noclobber(thread_dir.join(format!("{name}.json"))).map_err(|e| e.error)?;
    Ok(())
}

/// Writes `name` (which holds every event of the files it replaces), then
/// removes the files in `replaces`. Only those: a file that arrived meanwhile,
/// say with a `git pull`, isn't in `name` and stays.
pub fn compact(dir: &Path, thread: &str, name: &str, content: &str, replaces: &[String]) -> io::Result<()> {
    for old in replaces {
        check_id(old)?;
    }
    add(dir, thread, name, content)?;
    let thread_dir = dir.join(thread);
    for old in replaces.iter().filter(|old| *old != name) {
        match fs::remove_file(thread_dir.join(format!("{old}.json"))) {
            Err(e) if e.kind() != io::ErrorKind::NotFound => return Err(e),
            _ => {}
        }
    }
    Ok(())
}

/// After `from` (a document or a folder) was renamed to `to`, moves its comments along.
pub fn moved(root: &Path, from: &Path, to: &Path) -> io::Result<()> {
    let (Some(old), Some(new)) = (dir_for(root, from), dir_for(root, to)) else {
        return Ok(());
    };
    if !old.exists() || new.exists() {
        return Ok(());
    }
    if let Some(parent) = new.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::rename(old, new)
}

#[derive(Serialize, Debug, PartialEq)]
pub struct Identity {
    pub name: String,
    pub email: String,
}

/// The git user (`user.name`, `user.email`) for `root`, which comments are
/// signed with. Asks git itself, so includes and per-repository settings
/// apply. `None` without git or without a name.
pub fn git_identity(root: &Path) -> Option<Identity> {
    let git = git_binary()?;
    let get = |key: &str| -> Option<String> {
        let out = Command::new(&git).args(["config", "--get", key]).current_dir(root).output().ok()?;
        let value = String::from_utf8(out.stdout).ok()?.trim().to_string();
        (out.status.success() && !value.is_empty()).then_some(value)
    };
    Some(Identity { name: get("user.name")?, email: get("user.email").unwrap_or_default() })
}

/// Apps opened from the Finder don't get the shell's PATH, so look where git
/// usually is. On macOS `/usr/bin/git` is a stub that offers to install the
/// developer tools when they're missing, so it's only used when they're there.
fn git_binary() -> Option<PathBuf> {
    if cfg!(target_os = "macos") {
        let found = ["/opt/homebrew/bin/git", "/usr/local/bin/git"]
            .into_iter()
            .map(PathBuf::from)
            .find(|p| p.is_file());
        if found.is_some() {
            return found;
        }
        let developer_dir = Command::new("/usr/bin/xcode-select").arg("-p").output().ok()?;
        let developer_dir = String::from_utf8(developer_dir.stdout).ok()?;
        let tools_git = Path::new(developer_dir.trim()).join("usr/bin/git");
        return tools_git.is_file().then(|| PathBuf::from("/usr/bin/git"));
    }
    Some(PathBuf::from("git"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(dir: &Path) -> Vec<(String, String)> {
        read(dir).unwrap().into_iter().map(|f| (f.thread, f.name)).collect()
    }

    #[test]
    fn finds_the_folder_of_a_document() {
        let root = Path::new("/notes");
        assert_eq!(
            dir_for(root, Path::new("/notes/docs/a.md")).unwrap(),
            Path::new("/notes/.mido/comments/docs/a.md")
        );
        assert_eq!(dir_for(root, root), None);
        assert_eq!(dir_for(root, Path::new("/elsewhere/a.md")), None);
    }

    #[test]
    fn accepts_only_plain_ids() {
        assert!(valid_id("01JBQ3W7Z8K2M4N6P8R0T2V4X6"));
        for id in ["", "..", "a/b", "a.json", "a b", "x\\y", &"a".repeat(65)] {
            assert!(!valid_id(id), "{id:?} should be refused");
        }
    }

    #[test]
    fn reads_nothing_without_comments() {
        let dir = tempfile::tempdir().unwrap();
        assert!(read(&dir.path().join("missing")).unwrap().is_empty());
    }

    #[test]
    fn adds_and_reads_files() {
        let dir = tempfile::tempdir().unwrap();
        add(dir.path(), "T1", "E2", "two").unwrap();
        add(dir.path(), "T1", "E1", "one").unwrap();
        add(dir.path(), "T2", "E3", "three").unwrap();
        fs::write(dir.path().join("T1/notes.txt"), "ignored").unwrap();
        let files = read(dir.path()).unwrap();
        assert_eq!(files[0], CommentFile { thread: "T1".into(), name: "E1".into(), content: "one".into() });
        assert_eq!(names(dir.path()), [("T1", "E1"), ("T1", "E2"), ("T2", "E3")].map(|(a, b)| (a.into(), b.into())));
    }

    #[test]
    fn never_replaces_a_file() {
        let dir = tempfile::tempdir().unwrap();
        add(dir.path(), "T1", "E1", "first").unwrap();
        assert!(add(dir.path(), "T1", "E1", "second").is_err());
        assert_eq!(fs::read_to_string(dir.path().join("T1/E1.json")).unwrap(), "first");
        let leftovers: Vec<_> = fs::read_dir(dir.path().join("T1")).unwrap().collect();
        assert_eq!(leftovers.len(), 1);
    }

    #[test]
    fn refuses_ids_that_escape_the_folder() {
        let dir = tempfile::tempdir().unwrap();
        assert!(add(dir.path(), "..", "E1", "x").is_err());
        assert!(add(dir.path(), "T1", "../E1", "x").is_err());
        assert!(compact(dir.path(), "T1", "E2", "x", &["../../a".into()]).is_err());
    }

    #[test]
    fn compacts_only_the_files_it_replaces() {
        let dir = tempfile::tempdir().unwrap();
        add(dir.path(), "T1", "E1", "one").unwrap();
        add(dir.path(), "T1", "E2", "two").unwrap();
        // Arrived after the app read the thread (a pull, say).
        add(dir.path(), "T1", "E3", "three").unwrap();
        compact(dir.path(), "T1", "E4", "one+two+resolve", &["E1".into(), "E2".into(), "gone".into()]).unwrap();
        assert_eq!(names(dir.path()), [("T1", "E3"), ("T1", "E4")].map(|(a, b)| (a.into(), b.into())));
    }

    #[test]
    fn moves_comments_with_their_document() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let comments = dir_for(root, &root.join("a.md")).unwrap();
        add(&comments, "T1", "E1", "one").unwrap();
        moved(root, &root.join("a.md"), &root.join("sub/b.md")).unwrap();
        assert!(!comments.exists());
        assert_eq!(names(&dir_for(root, &root.join("sub/b.md")).unwrap()).len(), 1);
        // Nothing to move.
        moved(root, &root.join("c.md"), &root.join("d.md")).unwrap();
    }
}
